services:
  castestor:
    build: 
      context: .
      args:
        UID: "1001"
        GID: "1001"
        UNAME: "cybuser"
    container_name: castestor
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    environment:
      BIND_ADDRESS: "0.0.0.0"

    command: "sh run.sh"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    user: "1001:1001"
    # restart: always

